name: Build Daily Signals

on:
  schedule:
    - cron: "10 10 * * 1-5"   # 06:10 America/New_York ≈ 10:10 UTC (adjust by DST as needed)
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build signals and OHLC
        run: |
          python scripts/build_signals.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/today.json public/ohlc/*.json
          git diff --cached --quiet || git commit -m "chore: refresh daily signals"
          git push
